### ISSUE TITLE
New android 14 update possibly causing crashes

### ISSUE THREAD

**Issue by voxvargr** [Chainfire/liveboot#11]
I updated to the release version from xda after the debug one worked from another issue here (thank you chainfire!) and then after almost a day I started having multiple crashes and reboots that were seemingly random and the only new app/mod was liveboot and after I uninstalled it and it stopped rebooting randomly. I know how to record logcats but don't they get erased on boot? So idk how id save one from a crash

I'm on stock rooted OnePlus oos 14 NA version

Please advise and I'll do whatever you want for me to collect but I won't be able to answer for about 12hrs just started a road trip with liveboot uninstalled and it's been stable the past hour with no reboots since uninstall

**Comment by Chainfire** [comment]
I think the only way you can catch this is hooking the phone up to a computer, and running `adb logcat` on that computer, hope the crash/reboot occurs and the log went over the wire containing the important information, and then you have it on your computer.

It should not be related, but nothing is impossible.

**Comment by voxvargr** [comment]
I will definitely try this after my trip but I'm going on a little over 6 hours after uninstalling only liveboot and absolutely no crashing/reboots since. Will test this after the trip when I have access to my computer. Also when it would crash and reboot - liveboot didn't work but my custom boot animation worked. But if I manually rebooted liveboot worked as intended, not sure if that makes a difference either.

**Comment by Chainfire** [comment]
No worries and no rush. For sure I'm not in one 😂

Very curious it doesn't show after a crash, would indicate different bootsequences somehow. And perhaps the custom boot animation conflicts with LiveBoot? Not sure how that would work.

Hopefully once you get a logcat of the actual crash that'll provide some hints.

**Comment by Senliast** [comment]
@spart0n654 which Magisk version do you have?

**Comment by voxvargr** [comment]
27

**Comment by Senliast** [comment]
Are you sure crashes doesn't happen anymore after you uninstall the app? I have the same problem, but it still exists after i uninstall the app. I catched a log here, if i understand right, the crash happens in LSPosed-Bridge:

[ 2024-03-22T00:28:02.288     1000:  1572:  2033 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:781)
	at java.util.TimSort.mergeAt(TimSort.java:518)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1344)
	at java.util.ArrayList.sort(ArrayList.java:1738)
	at java.util.Collections.sort(Collections.java:210)
	at com.android.server.am.PhantomProcessList.trimPhantomProcessesIfNecessary(PhantomProcessList.java:436)
	at com.android.server.am.ActivityManagerConstants$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
[ 2024-03-22T00:28:02.288     1000:  1572:  2033 E/AndroidRuntime  ] *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:781)
	at java.util.TimSort.mergeAt(TimSort.java:518)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1344)
	at java.util.ArrayList.sort(ArrayList.java:1738)
	at java.util.Collections.sort(Collections.java:210)
	at com.android.server.am.PhantomProcessList.trimPhantomProcessesIfNecessary(PhantomProcessList.java:436)
	at com.android.server.am.ActivityManagerConstants$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
[ 2024-03-22T00:28:02.327     1000:  1572:  2033 I/LSPosed-Bridge  ] [AppErrorsTracking][W][android] Received but got null ProcessRecord
[ 2024-03-22T00:28:02.730        0:   900:   988 W/LSPosedService  ] notificationManager is dead
[ 2024-03-22T00:28:02.738        0:   900: 11261 W/LSPosedService  ] am is dead
[ 2024-03-22T00:28:02.741        0:   900:   989 W/LSPosedService  ] um is dead
[ 2024-03-22T00:28:02.741        0:   900:   988 W/LSPosedService  ] pm is dead
[ 2024-03-22T00:28:02.742        0:   900: 11261 I/LSPosedService  ] service activity is dead. 
[ 2024-03-22T00:28:02.744        0:   900: 11261 I/LSPosedService  ] clear ServiceManager
[ 2024-03-22T00:28:02.744        0:   900: 11261 W/LSPosedService  ] system server died
[ 2024-03-22T00:28:02.749        0:   900:   900 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2024-03-22T00:28:03.750        0:   900:   900 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2024-03-22T00:28:04.751        0:   900:   900 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2024-03-22T00:28:04.849        0:   881:  1687 I/Magisk          ] ** zygote restarted
[ 2024-03-22T00:28:04.988        0: 29541: 29541 I/Magisk          ] zygisk64: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
[ 2024-03-22T00:28:04.988        0: 29541: 29541 I/Magisk          ] zygisk64: replaced com/android/internal/os/Zygote#nativeForkSystemServer
[ 2024-03-22T00:28:04.988        0: 29541: 29541 I/Magisk          ] zygisk64: replaced com/android/internal/os/Zygote#nativeSpecializeAppProcess
[ 2024-03-22T00:28:05.168        0: 29540: 29540 I/Magisk          ] zygisk32: replaced com/android/internal/os/Zygote#nativeForkAndSpecialize
[ 2024-03-22T00:28:05.168        0: 29540: 29540 I/Magisk          ] zygisk32: replaced com/android/internal/os/Zygote#nativeForkSystemServer
[ 2024-03-22T00:28:05.168        0: 29540: 29540 I/Magisk          ] zygisk32: replaced com/android/internal/os/Zygote#nativeSpecializeAppProcess
[ 2024-03-22T00:28:05.751        0:   900:   900 I/LSPosedService  ] service activity is not started, wait 1s.
[ 2024-03-22T00:28:06.051        0: 29726: 29726 I/Magisk          ] * Launching zygiskd64
[ 2024-03-22T00:28:06.052        0: 29726: 29729 I/LSPosed         ] ZygiskCompanion: welcome to LSPosed!
[ 2024-03-22T00:28:06.052        0: 29726: 29729 I/LSPosed         ] ZygiskCompanion: version v1.9.2 (7024)
[ 2024-03-22T00:28:06.178     1000: 29696: 29696 I/LSPosed         ] Loading xposed for system/1000
[ 2024-03-22T00:28:06.271        0:   900:   974 W/lspd            ] Reducing the number of considered missed Gc histogram windows from 339 to 100

Do you have LSPosed installed?

**Comment by voxvargr** [comment]
I do have LSposed installed and since I uninstalled liveboot I haven't had a single crash/unexpected reboot. I've kept my other apps, modules, etc updated and reboot accordingly but no crashes or anything. I can try to leave liveboot installed again and I will report back

**Comment by Senliast** [comment]
Yes, and if the crash happen - you can export crashlog from LSPosed (detailed log tab, then the save icon, then from the saved zip, the /log/verbose... text file should be enough) and upload it here. If you could do it - it would be helpfull. Thank you.

**Comment by voxvargr** [comment]
So far no abnormal issues so I think we can close this
