### ISSUE TITLE
License is applied improperly

### ISSUE THREAD

**Issue by KOLANICH** [Chainfire/liveboot#2]
You have posted a GPL license notice into a license file. It is incorrect. Instead license file must contain an unmodified text of the license. The license notice should be put into some source code file. After that GitHub should detect the license correctly.

**Comment by Chainfire** [comment]
The full license text is in COPYING, as GNU does.

**Comment by KOLANICH** [comment]
Yes, but LICENSE file confuses GH autodetection logic. Its content usually is not placed into such a file, but into source code files.

**Comment by Chainfire** [comment]
🤷‍♂️
